# deploy from dev/local machine via (which will create git tag):
# npm version patch -m "%s release"
dist: xenial
language: node_js
node_js:
  - "10"
git:
  depth: 2147483647
  branch: master
branches:
  only:
    - master
    - "/v*/"
script:
  #- printenv
  - "npm test"
before_deploy:
  - "npm run gen-docs"
deploy:
  - provider: npm
    email: "ugate.public@gmail.com"
    api_key: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      all_branches: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target-branch: gh-pages
    local-dir: docs
    on:
      tags: true # only on tagging commit
      all_branches: true
after_deploy:
  - "git push --tags"